# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
notifications:
  email: false
services:
  - xvfb
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("Gillespie"); Pkg.test("Gillespie"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Gillespie")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Gadfly"); using Documenter; using Gadfly;'
  - julia -e 'using Pkg; cd(Pkg.dir("Gillespie")); include(joinpath("docs", "make.jl"))'
